version: 2
jobs:
  build:
    working_directory: /work
    docker:
      - image: node:16.6.1
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: release
          command: npm run release
